apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-role-2
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
  roles:
    - name: read-sync
      description: "this role can be used for reading applications"
      policies:
        - p, proj:project-role-2:read-sync, applications, get, project-role-2/*, allow
        - p, proj:project-role-2:read-sync, applications, sync, project-role-2/*, allow
