apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-directory-sync-phases-waves
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
            #exclude: 'service.yml'
            # include: '{serviceaccount.yml,service.yml}'
      recurse: true
    path: v07-argocd-sync-phases-waves/sync-phases-waves-manifests-examples
    repoURL: https://github.com/saeed-didar/argocd-tutorial.git
    targetRevision: main
    #  syncPolicy:
          #   syncOptions:
          #    - CreateNamespace=true
