apiVersion: batch/v1
kind: Job
metadata:
  name: mattermost-post-job-success
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
        - name: mattermost-success
          image: docker.io/library/mattermost:final
          imagePullPolicy: Never          
          command: [ "python3", "mattermost_api.py"]
          env:
          - name: message
            value: "MESSAGE FROM ARGOCD: The last sync is:  *** Sync OK :) ***"
          - name: url
            value: "192.168.209.210"
          - name: token
            value: "7wqdtcf59tdr8kqyirncxkdegc"
          - name: scheme
            value: "https"
          - name: port
            value: "443"
          - name: channel_name
            value: "saba-channel"
          - name: team_name
            value: "saba-home"
          - name: PYTHONHTTPSVERIFY
            value: "0"  # <- disables SSL certificate verification
      restartPolicy: Never
  backoffLimit: 0
